name: embryo_crop_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - tifffile
  - tqdm
  - numpy
  - scikit-image
  - opencv
  - scipy
  - pyclesperanto
  - gitpython
  - selectors:
    - os: linux
      dependencies:
        - ocl-icd-system # for pyclesperanto
    - os: osx
      dependencies:
        - ocl_icd_wrapper_apple # for pyclesperanto